/*

Chicago Car Crashes Data Analysis

*/


SELECT COUNT(CRASH_RECORD_ID) AS Count_of_Accident,SUM(INJURIES_TOTAL) AS Total_Injuries,
SUM(INJURIES_FATAL) AS Total_Fatal_Injuries 
FROM car_crash

--Looking at fatal injury percentage 

SELECT COUNT(INJURIES_FATAL) AS Count_of_Fatal_Injuries,
SUM(INJURIES_FATAL)/SUM(INJURIES_TOTAL) *100 AS Fatal_Injury_Percentage  
FROM car_crash

-- Looking at count of accident,total injuries and injury rate in accidents to weather condition

SELECT WEATHER_CONDITION,COUNT(CRASH_RECORD_ID) AS Count_of_Accident,
SUM(INJURIES_TOTAL) AS Total_Injuries, 
SUM(INJURIES_TOTAL)/COUNT(CRASH_RECORD_ID)*100 AS Injury_Rate_in_Accidents FROM car_crash 
GROUP BY WEATHER_CONDITION ORDER BY COUNT(CRASH_RECORD_ID) DESC

-- Looking at count of accident,total injuries and injury rate in accidents to lighting condition

SELECT LIGHTING_CONDITION,COUNT(CRASH_RECORD_ID) AS Count_of_Accident,
SUM(INJURIES_TOTAL) AS Total_Injuries, 
SUM(INJURIES_TOTAL)/COUNT(CRASH_RECORD_ID)*100 AS Injury_Rate_in_Accidents
FROM car_crash 
GROUP BY LIGHTING_CONDITION ORDER BY COUNT(CRASH_RECORD_ID) DESC

-- Looking at count of accident,total injuries and injury rate in accidents to roadway surface condition

SELECT ROADWAY_SURFACE_COND,COUNT(CRASH_RECORD_ID) AS Count_of_Accident,
SUM(INJURIES_TOTAL) AS Total_Injuries, 
SUM(INJURIES_TOTAL)/COUNT(CRASH_RECORD_ID)*100 AS Injury_Rate_in_Accidents 
FROM car_crash 
GROUP BY ROADWAY_SURFACE_COND 
ORDER BY COUNT(CRASH_RECORD_ID) DESC

--Looking at top 10 primary causes of the crash.

SELECT TOP 10 PRIM_CONTRIBUTORY_CAUSE,COUNT(CRASH_RECORD_ID) AS Count_of_Accident 
FROM car_crash GROUP BY  PRIM_CONTRIBUTORY_CAUSE 
ORDER BY  COUNT(CRASH_RECORD_ID) DESC

-- Looking  at most severe injury percentage

WITH injuries AS (
SELECT MOST_SEVERE_INJURY,COUNT(CRASH_RECORD_ID) AS INJURY_COUNT
FROM car_crash WHERE  MOST_SEVERE_INJURY NOT LIKE 'NULL'
GROUP BY MOST_SEVERE_INJURY  )

SELECT MOST_SEVERE_INJURY,
INJURY_COUNT/CAST((SELECT COUNT(CRASH_RECORD_ID) FROM car_crash)  AS DECÝMAL(10,2))*100 
AS Most_Severe_Injury_Percentage  
FROM injuries ORDER BY AS Most_Severe_Injury_Percentage DESC

--Looking at the accident of count per damage category

WITH accident_damage AS (
SELECT DAMAGE,COUNT(CRASH_RECORD_ID) AS INJURY_COUNT
FROM car_crash WHERE  DAMAGE NOT LIKE 'NULL'
GROUP BY DAMAGE  )

SELECT DAMAGE,
INJURY_COUNT/CAST((SELECT COUNT(CRASH_RECORD_ID) FROM car_crash)  AS DECÝMAL(10,2))*100 
AS Damage_vs_Count_Accident
FROM accident_damage ORDER BY Damage_vs_Count_Accident DESC

--Looking at count of acccidents by days of the week and hours

WITH week_days_name AS (
SELECT CRASH_HOUR,CRASH_DAY_OF_WEEK,CRASH_RECORD_ID, CASE   
WHEN CONVERT(NVARCHAR(225),CRASH_DAY_OF_WEEK)= '1' THEN 'Sunday'
WHEN CONVERT(NVARCHAR(225),CRASH_DAY_OF_WEEK) = '2' THEN 'Monday'
WHEN CONVERT(NVARCHAR(225),CRASH_DAY_OF_WEEK)= '3' THEN 'Tuesday'
WHEN CONVERT(NVARCHAR(225),CRASH_DAY_OF_WEEK)= '4' THEN 'Wednesday'
WHEN CONVERT(NVARCHAR(225),CRASH_DAY_OF_WEEK)= '5' THEN 'Thursday'
WHEN CONVERT(NVARCHAR(225),CRASH_DAY_OF_WEEK) = '6' THEN 'Friday'
WHEN CONVERT(NVARCHAR(225),CRASH_DAY_OF_WEEK) = '7' THEN 'Saturday'
ELSE  CONVERT(NVARCHAR(225),CRASH_DAY_OF_WEEK)
END  AS CRASH_DAY_OF_WEEK_DAY
FROM car_crash )

SELECT CRASH_HOUR,CRASH_DAY_OF_WEEK_DAY,COUNT(CRASH_RECORD_ID) AS Count_of_Accident
FROM week_days_name GROUP BY CRASH_DAY_OF_WEEK_DAY,CRASH_HOUR 
ORDER BY COUNT(CRASH_RECORD_ID) DESC

--Looking at count of acccidents by months and years

SELECT CRASH_MONTH,YEAR(CRASH_DATE),COUNT(CRASH_RECORD_ID) 
FROM car_crash GROUP BY YEAR(CRASH_DATE),CRASH_MONTH  
ORDER BY COUNT(CRASH_RECORD_ID) DESC

--Looking at count of acccidents by days of the week  

WITH week_days_name AS (
SELECT CRASH_DAY_OF_WEEK,CRASH_RECORD_ID, CASE   
WHEN CONVERT(NVARCHAR(225),CRASH_DAY_OF_WEEK)= '1' THEN 'Sunday'
WHEN CONVERT(NVARCHAR(225),CRASH_DAY_OF_WEEK) = '2' THEN 'Monday'
WHEN CONVERT(NVARCHAR(225),CRASH_DAY_OF_WEEK)= '3' THEN 'Tuesday'
WHEN CONVERT(NVARCHAR(225),CRASH_DAY_OF_WEEK)= '4' THEN 'Wednesday'
WHEN CONVERT(NVARCHAR(225),CRASH_DAY_OF_WEEK)= '5' THEN 'Thursday'
WHEN CONVERT(NVARCHAR(225),CRASH_DAY_OF_WEEK) = '6' THEN 'Friday'
WHEN CONVERT(NVARCHAR(225),CRASH_DAY_OF_WEEK) = '7' THEN 'Saturday'
ELSE  CONVERT(NVARCHAR(225),CRASH_DAY_OF_WEEK)
END  AS CRASH_DAY_OF_WEEK_DAY
FROM car_crash )

SELECT CRASH_DAY_OF_WEEK_DAY,COUNT(CRASH_RECORD_ID) AS Count_of_Accident
FROM week_days_name GROUP BY CRASH_DAY_OF_WEEK_DAY 
ORDER BY COUNT(CRASH_RECORD_ID) DESC

--Looking at count of accidents by months

WITH months_name AS (
SELECT CRASH_MONTH,CRASH_RECORD_ID, CASE   
WHEN CONVERT(NVARCHAR(225),CRASH_MONTH)= '1' THEN 'January'
WHEN CONVERT(NVARCHAR(225),CRASH_MONTH) = '2' THEN 'February'
WHEN CONVERT(NVARCHAR(225),CRASH_MONTH)= '3' THEN 'March'
WHEN CONVERT(NVARCHAR(225),CRASH_MONTH)= '4' THEN 'April'
WHEN CONVERT(NVARCHAR(225),CRASH_MONTH)= '5' THEN 'May'
WHEN CONVERT(NVARCHAR(225),CRASH_MONTH) = '6' THEN 'June'
WHEN CONVERT(NVARCHAR(225),CRASH_MONTH) = '7' THEN 'July'
WHEN CONVERT(NVARCHAR(225),CRASH_MONTH) = '8' THEN 'August'
WHEN CONVERT(NVARCHAR(225),CRASH_MONTH) = '9' THEN 'September'
WHEN CONVERT(NVARCHAR(225),CRASH_MONTH) = '10' THEN 'October'
WHEN CONVERT(NVARCHAR(225),CRASH_MONTH) = '11' THEN 'November'
WHEN CONVERT(NVARCHAR(225),CRASH_MONTH) = '12' THEN 'December'
ELSE  CONVERT(NVARCHAR(225),CRASH_MONTH)
END  AS CRASH_MONTH_NAME
FROM car_crash )

SELECT CRASH_MONTH_NAME,COUNT(CRASH_RECORD_ID) AS Count_of_Accident
FROM months_name GROUP BY CRASH_MONTH_NAME 
ORDER BY COUNT(CRASH_RECORD_ID) DESC

--Looking at count of accidents by time of day

WITH times AS (
SELECT CRASH_HOUR,CRASH_RECORD_ID,CASE 
WHEN CRASH_HOUR BETWEEN 6 AND 11  THEN 'Morning'
WHEN CRASH_HOUR BETWEEN 12 AND 17  THEN 'Noon'
WHEN CRASH_HOUR BETWEEN 18 AND 23  THEN 'Evening'
WHEN CRASH_HOUR BETWEEN 0 AND 5 THEN 'Night'
ELSE 'Unknown' 
END  AS Time_Period FROM car_crash)

SELECT Time_Period,COUNT(CRASH_RECORD_ID) AS Count_of_Accident
FROM times GROUP BY time_period 
ORDER BY COUNT(CRASH_RECORD_ID) DESC

--Looking at count of accidents by years

SELECT YEAR(CRASH_DATE),COUNT(CRASH_RECORD_ID) AS Count_of_Accident 
FROM car_crash GROUP BY YEAR(CRASH_DATE) 
ORDER BY COUNT(CRASH_RECORD_ID) DESC

--Looking at count of accidents by street's names and no

SELECT STREET_NAME,STREET_NO,COUNT(CRASH_RECORD_ID) AS Count_of_Accident
FROM car_crash GROUP BY  STREET_NAME,STREET_NO 
ORDER BY COUNT(CRASH_RECORD_ID) DESC







  